apiVersion: v1
data:
  MONGODB_URI: mongodb://mongodb:27017/wanderlust
  #mongodb://mongo:27017
  REDIS_URL: redis://redis:6379
  #redis://redis:6379
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: backend-backend-env-docker
  name: backend-env-docker
