apiVersion: v1
data:
  VITE_API_PATH: http://192.168.49.2:30662
  #http://backend:5000
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: frontend-frontend-env-docker
  name: frontend-env-docker
